id: P004226
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105884
  title: ཕྱག་རྒྱ་ཆེན་པོའི་ལྟ་བ་སྤྱི་ཁྱབ་ཏུ་ངོ་སྤྲོད་པའི་ཁྲིད་ཡིག་ཕྱོགས་སྒྲིག
  author: ''
  volumes:
    1bb259fb25a24fdcbee58d1d72802dc8:
      image_group_id: I1PD105886
      title: ''
      volume_number: 1
      total_pages: 256
      base_file: v001.txt
