id: I4A1923CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:55:41+00:00'
last_modified: '2022-06-07T21:13:24.262995+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105884
  title: ཕྱག་རྒྱ་ཆེན་པོའི་ལྟ་བ་སྤྱི་ཁྱབ་ཏུ་ངོ་སྤྲོད་པའི་ཁྲིད་ཡིག་ཕྱོགས་སྒྲིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9809':
      image_group_id: I1PD105886
      title: ''
      total_pages: 256
      order: 1
      base_file: 9809.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
